data_dir: "/home/jperez/data/HKH/processed_L07_2005_phys64_s1"
normalize: "mean-std"
gpu_rank: 0
folder_name: "runs"
run_name: "phys64_s1"
# cleanice_model: "/home/jperez/programming/glacier_mapping/runs/jose_physv2_64/models/model_best.pt"
# debris_model: "/home/jperez/programming/glacier_mapping/runs/jose_physv2_64/models/model_best.pt"
out_processed_dir: "pred_runs/"
class_names: ["BG", "CI", "Debris"]
use_channels_cleanice: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
threshold: [0.5, 0.5, 0.5]
model_opts_cleanice:
  args:
    # inchannels: 11
    # outchannels: 3
    net_depth: 4
    dropout: 0.00000001
    spatial: True
    first_channel_output: 32
# model_opts_debris:
#   args:
#     inchannels: 11
#     outchannels: 3
#     net_depth: 4
#     dropout: 0.00000001
#     spatial: True
#     first_channel_output: 32
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
# use_channels_debris: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
