# Training configuration
training_opts:
  dataset_name: "bibek_w512_o64_f1"
  run_name: "baseline_CI"
  epochs: 500
  fine_tune: False
  find_lr: False
  early_stopping: 150
  full_eval_every: 10
  num_viz_samples: 4

loader_opts:
  batch_size: 8
  use_channels: [0, 1, 2, 3, 4, 5, 6, 7]
  output_classes: [1]
  normalize: "mean-std"
  class_names: ["BG", "CleanIce", "Debris"]

metrics_opts:
  metrics: ["IoU", "precision", "recall"]
  threshold: [0.5]

loss_opts:
  name: "custom"
  masked: False
  gaussian_blur_sigma: None
  label_smoothing: 0
  use_unified: False

model_opts:
  args:
    net_depth: 4
    dropout: 0.1
    spatial: True
    first_channel_output: 32

optim_opts:
  name: "AdamW"
  args:
    lr: 0.0003
    weight_decay: 5e-5

scheduler_opts:
  name: "OneCycleLR"
  args:
    max_lr: 0.001
    pct_start: 0.3
    anneal_strategy: "cos"

