training_opts:
  output_dir: "/data/jperez/programming/glacier_mapping/newruns/"
  run_name: "baseline_ci"
  gpu_rank: 0
  epochs: 251
  fine_tune: False
  find_lr: False
loader_opts:
  processed_dir: "/data/jperez/datasets/HKH/baseline/"
  batch_size: 8 # 14 # 8
  use_channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] # ["B1", "B2", "B3", "B4", "B5", "B6_VCID1", "B6_VCID2", "B7", "elevation", "slope", 'physics']
  output_classes: [1] # 0=BG, 1=CI, 2=Debris
  normalize: "mean-std" # "min-max" or "mean-std"
  physics_channel: 10 # For physics experiments (No need to change)
  class_names: ["BG", "CleanIce", "Debris"] # All class names in the dataset (No need to change)
metrics_opts:
  metrics: ["IoU", "precision", "recall"]
  threshold: [0.5, 0.5, 0.5]
loss_opts:
  name: "custom"
  masked: True
  weights: [1.0]
  gaussian_blur_sigma: None
  label_smoothing: 0.1
  alpha: 0.9
model_opts:
  args:
    net_depth: 4
    dropout: 0.1
    spatial: True
    first_channel_output: 32
optim_opts:
  name: "Adam"
  args:
    lr: 0.0003
